// This file is generated by fl_build. Do not edit.
// ignore_for_file: prefer_single_quotes

abstract class BuildData {
  static const String name = "AzadHub";
  static const int build = 1491;
  static const int script = 73;
}
